### ISSUE TITLE
Possible bug when using single array

### ISSUE THREAD

**Issue by davecoggins** [mmikkel/Retcon-Craft#1]
Hi

I'm running into a bug when using the same code from my Craft 2 setup on Craft 3. I've simplified to just a single example:

The following works:

```{{ entry.body | retconAttr('h3', { class: 'heading' }) }}```

However when passed in a single array, this throws an error:

    {{ entry.body | retcon([
        ['attr', 'h3', { class: 'heading' }]
    ]) }}

The error I get is:

```Missing argument 2 for mmikkel\retcon\services\RetconService::attr(), called in .....vendor/mmikkel/retcon/src/services/RetconService.php on line 71 and defined```

Am I doing something wrong?

Cheers
Dave

**Comment by mmikkel** [comment]
Hi @davecoggins – thanks for contributing; I'm looking into it ASAP.

**Comment by mmikkel** [comment]
This issue should be resolved in [v. 2.0.1](https://github.com/mmikkel/Retcon-Craft/releases/tag/2.0.1).

**Comment by davecoggins** [comment]
Hi @mmikkel,

Thanks for looking into this so quickly for me, I can confirm all is working well 👍 

Btw - retcon is an awesome plugin, works really well with tailwindcss. 

Cheers
Dave

**Comment by mmikkel** [comment]
Awesome @davecoggins – thanks for the kind words. Let me know if you encounter any other issues going forward!
