### ISSUE TITLE
Srcset examples are wrong (v2.0.12)

### ISSUE THREAD

**Issue by haabe** [mmikkel/Retcon-Craft#12]
According to the [examples](https://github.com/mmikkel/Retcon-Craft/wiki/srcset), the parameters are transform, sizes, base64-encoding.

The source code has a selector parameter inbetween transform and sizes. Not defining the selector causes the plugin to crash when you define sizes.

**Comment by mmikkel** [comment]
Hi @haabe – thanks for reporting. The signature for `retconSrcset` changed a bit between Craft 2 and Craft 3, and I've neglected to update the docs. Will fix ASAP :)
