### ISSUE TITLE
retconOnly - nth-of-type sometimes works, sometimes not

### ISSUE THREAD

**Issue by piotrpog** [mmikkel/Retcon-Craft#13]
I noticed that using `nth-of-type` in selector works when i do this:

```
 {% set html %}
<img src="1" alt="">
<img src="2" alt="">
{% endset %}
{{ html | retconOnly( 'img:nth-of-type(1)' ) }}
```
But does not work when `img` tags are wrapped in `<figure>` like this:

```
{% set html %}
<figure><img src="1" alt="" /></figure>
<figure><img src="2" alt="" /></figure>
{% endset %}
{{ html | retconOnly( 'img:nth-of-type(1)' ) }}
```

In such a situation, whole HTML is returned.

**Comment by mmikkel** [comment]
Hi @piotrpog, thanks for reporting.

This _might_ be an issue with the Symfony DomCrawler library and not Retcon per-se (in which case a fix might be difficult to accomplish), but I'll take a closer look ASAP and see if there's anything I can do about it.

**Comment by mmikkel** [comment]
Hi @piotrpog, the `nth-of-type` selector is indeed [not supported in DomCrawler](https://symfony.com/doc/3.3/components/css_selector.html#limitations-of-the-cssselector-component).

**Comment by piotrpog** [comment]
@mmikkel 
Yet it somehow IS supported :) I don't mean to say that you have to fix domcrawler itself, but in my first example, it actually worked alright.

**Comment by mmikkel** [comment]
@piotrpog Yeah, I agree that the behaviour is odd (in that it's not consistent)...
