### ISSUE TITLE
retconOnly - return null when element was not found at all

### ISSUE THREAD

**Issue by piotrpog** [mmikkel/Retcon-Craft#14]
When I use `retconOnly` to look for example for images, and there are no images present in html, whole html is returned. 

Wouldnt it make more sense to return null in such a situation? Or make such behaviour optional, by adding a new parameter to filter.

**Comment by mmikkel** [comment]
Hi @piotrpog, thanks for reporting.

I concur that `retconOnly` should return `null` (or an empty string) if the selector matches no elements. I'll get a fix out soon-ish!

**Comment by mmikkel** [comment]
Sorry for the delay – resolved in [Retcon 2.2.1](https://github.com/mmikkel/Retcon-Craft/releases/tag/2.2.1).
