### ISSUE TITLE
allow retconAttr use objects for styles

### ISSUE THREAD

**Issue by piotrpog** [mmikkel/Retcon-Craft#15]
Lately, I have been using `attr` function added in craft 3,2 and `tag` function added in craft 3.3. These functions can take objects consisting of key-value pairs and transform them into inlined css - like this object:
```
{% set styles = {
	'position': 'relative',
	'padding-bottom': '56.25%',
	'height': '0',
	'overflow': 'hidden',
	'max-width': '100%',
	'margin': '0px',
} %}
```
Unfortunately, I cannot use such an object with `retconAttr` function, i have pass css to it as a string: 
```
'position: absolute; top: 0; left: 0; width: 100%; height: 100%;'
```

**Comment by mmikkel** [comment]
This is resolved in [Retcon v. 2.4.0](https://github.com/mmikkel/Retcon-Craft/releases/tag/2.4.0) – the `retconAttr` filter now mostly behaves like the native `attr` filter, including support for arrays and object attribute values.
