### ISSUE TITLE
Plugin won't install

### ISSUE THREAD

**Issue by rtgoodwin** [mmikkel/Retcon-Craft#18]
Ok this is a tricky one. 

Craft 3.3.9, all dependencies up to date. 

Followed the instructions to `require` the package, and ran `composer update`. Verified:
- package is in JSON and lock
- `vendor/mmikkel/retcon` directory exists
- retcon is listed in `plugins.php`
- Retcon is shown in General->Plugins as not installed

Trying to install from this screen, or `craft install/plugin retcon` both result in `No plugin exists with the handle "retcon"`. 

Tried `composer remove` and reinstall, no avail. 

At a loss here. All help welcome :) (Trying here first before going to Craft GH.)

**Comment by mmikkel** [comment]
Hi @rtgoodwin - this is a new one.

Can you open up a file called `vendor/craftcms/plugins.php`, and see if there's an entry like the below in there:

```php
'mmikkel/retcon' => 
  array (
    'class' => 'mmikkel\\retcon\\Retcon',
    'basePath' => $vendorDir . '/mmikkel/retcon/src',
    'handle' => 'retcon',
    'aliases' => 
    array (
      '@mmikkel/retcon' => $vendorDir . '/mmikkel/retcon/src',
    ),
    'name' => 'Retcon',
    'version' => '2.0.12',
    'schemaVersion' => '1.0.0',
    'description' => 'Powerful Twig filters for mutating and querying HTML',
    'developer' => 'Mats Mikkel Rummelhoff',
    'developerUrl' => 'https://vaersaagod.no',
    'changelogUrl' => 'https://raw.githubusercontent.com/mmikkel/Retcon-Craft/master/CHANGELOG.md',
    'hasCpSettings' => false,
    'hasCpSection' => false,
    'components' => 
    array (
    ),
  ),
```

**Comment by rtgoodwin** [comment]
Yep, entry is there:
``` 
 'mmikkel/retcon' =>
  array (
    'class' => 'mmikkel\\retcon\\Retcon',
    'basePath' => $vendorDir . '/mmikkel/retcon/src',
    'handle' => 'retcon',
    'aliases' =>
    array (
      '@mmikkel/retcon' => $vendorDir . '/mmikkel/retcon/src',
    ),
    'name' => 'Retcon',
    'version' => '2.0.12',
    'schemaVersion' => '1.0.0',
    'description' => 'Powerful Twig filters for mutating and querying HTML',
    'developer' => 'Mats Mikkel Rummelhoff',
    'developerUrl' => 'https://vaersaagod.no',
    'documentationUrl' => 'https://github.com/mmikkel/Retcon-Craft/blob/master/README.md',
    'changelogUrl' => 'https://raw.githubusercontent.com/mmikkel/Retcon-Craft/master/CHANGELOG.md',
    'hasCpSettings' => false,
    'hasCpSection' => false,
    'components' =>
    array (
    ),
  ),
```
> If it does, I'm honestly stumped. Have you tried nuking the vendor folder completely and doing a composer install --no-interaction --prefer-dist --optimize-autoloader?

I haven't, as this is a production site; although I'm told this is generally OK, some reassurance (or ideas to back up properly) would be nice :) 

Honestly I haven't tried just _using_ the plugin, since the CP doesn't report it as installed. 

I'm on the Craft Discord server (RichardG) if you want to hit me up for more questions as well.  Thanks for looking into it!

**Comment by rtgoodwin** [comment]
I just noted the `documentationUrl` is different in mine; not sure if that's any kind of clue.

**Comment by mmikkel** [comment]
To be honest, I have no idea what could cause this behaviour... I'd get in touch with P&T to see if they've encountered it before.
