### ISSUE TITLE
retconTransform - image not found error

### ISSUE THREAD

**Issue by piotrpog** [mmikkel/Retcon-Craft#22]
When i use `retconTransform` filter on redactor field, retcon throws error that images within redactor field were not found, which is not the case. Image file path gets duplicated in error:

```
Image /path_on_server/test/esn/web/test/esn/web/uploads/files/judge1.jpg not found
```

Interestingly, when i install Imager, this error disappears.

**Comment by mmikkel** [comment]
Not able to reproduce this.
