### ISSUE TITLE
Question: Using with ImageOptimze for transforms

### ISSUE THREAD

**Issue by tom-byrom** [mmikkel/Retcon-Craft#27]
Hello!
Just came across your plugin as was looking for a solution to incorporate image transforms with Redactor Field Images.

This plugin looks like a life save for a number or really useful things when it comes to Redactor - so glad I found it.

I've looked at your transform docs and you integrate well with Imager X which I didn't use and instead created all my transforms with [ImageOptimze](https://plugins.craftcms.com/image-optimize)

Have you seen any examples or have worked on integrating transforms with this popular transform plugin?

If you have any info that would be great. Before I look at other options

Thanks
Tom

**Comment by mmikkel** [comment]
I’ve never used ImageOptimize or looked into how it works, but I *think* it just augments Craft’s native transform methods... which is what Retcon uses if Imager is not installed. Could be that it just works out of the box? :)

If not, I’m unlikely to add anything to support it TBH. But, I’d probably accept a pull request!
