### ISSUE TITLE
Craft 4 compatibility?

### ISSUE THREAD

**Issue by rob-baker-ar** [mmikkel/Retcon-Craft#35]
As above, will the plugin need a new version for Craft 4?

Thanks.

**Comment by mmikkel** [comment]
Yeah, I'll have a Craft 4 compatible version out in time for the GA.

**Comment by mmikkel** [comment]
Just tagged [Retcon v. 2.4.0](https://github.com/mmikkel/Retcon-Craft/releases/tag/2.4.0), which is compatible with Craft 4.0.
