### ISSUE TITLE
Transform fails if image is svg

### ISSUE THREAD

**Issue by espensgr** [mmikkel/Retcon-Craft#38]
We are using the `retconSrcset` on a redactor field, that can add images.
If you add an svg it fails as imager-x cant do that. Is it possible to skip svg files in the selector for `retconSrcset`?
Or is this an imager-x setting, or bug?

**Comment by mmikkel** [comment]
The thing is that (AFAIK) Imager _can_ transform SVGs, it depends on the transformer its using. In most cases though, I guess it isn't able to (and you wouldn't want it to), so I guess it'd make sense if Retcon didn't attempt to transform SVGs at all, as a default.

I'll have a think on how to approach this – but in the meantime, a quick workaround is to use the Retcon selector to avoid transforming any SVG files, i.e. something like:

```twig
{{ entry.redactorField|retconSrcset(
    [
        {width: 375},
        {width: 480},
        {width: 768}
    ],
    'img:not([src$=".svg"])',
    '(min-width: 40em) 80vw, 100vw'
) }}
```

**Comment by espensgr** [comment]
that makes sense, thanks for the solution, will implement it 👍

**Comment by mmikkel** [comment]
Circling back to this, I think I found a decent solution.

From the next release forward, Retcon will respect [Imager's `safeFileFormats` setting](https://imager-x.spacecat.ninja/configuration.html#safefileformats-array) (defaults to `['jpg', 'jpeg', 'gif', 'png']` when using Imager to transform images. I.e. the `retconTransform` and `retconSrcset` filters will no longer attempt to transform SVGs or other non-safe formats, unless those formats have been added to the `safeFileFormats` setting in Imager's config file.

**Comment by anita-chouhan** [comment]
Hi, we have a project with [_Imager_](https://plugins.craftcms.com/imager) and _Retcon_ plugins. We recently upgraded the _Retcon_ plugin to the version `2.7.0` and found that it's giving errors on image transforms:

<img width="950" alt="Screenshot 2023-10-27 at 5 03 05 PM" src="https://github.com/mmikkel/Retcon-Craft/assets/30666052/9189fae0-10e8-4b5a-8baa-0d7dace2da94">

### Additional info

- Craft version: 3.9.5
- Retcon plugin version: 2.7.0
- Imager plugin version: 2.4.0

**Comment by mmikkel** [comment]
@anita-chouhan Responded in a new issue: https://github.com/mmikkel/Retcon-Craft/issues/66
