### ISSUE TITLE
Add height and width attributes to images based on their size

### ISSUE THREAD

**Issue by stuible** [mmikkel/Retcon-Craft#42]
I would love if there was a way to add the correct width and height attributes to all images within my HTML.  It's frustrating that Craft CMS doesn't do this automatically and this plugin could really fill that gap.  Thanks for all the great work!

**Comment by mmikkel** [comment]
The next Retcon release will include a new `retconDimensions` filter, which will set the `width` and `height` attributes for image nodes (provided the attributes are missing, and the image referenced in the `src` attribute is a local image file):

```twig
{{ entry.ckEditorField | retconDimensions }}
```
