### ISSUE TITLE
Undefined array key "width"

### ISSUE THREAD

**Issue by espensgr** [mmikkel/Retcon-Craft#43]
Seems to be an error in the latest release

![image](https://user-images.githubusercontent.com/3862891/185870079-bf3d8768-3cf1-4950-a009-22d2e0c3bff3.png)

I'm using the `retconSrcset` in an [Article Editor](https://plugins.craftcms.com/craft-article?craft3) field with an asset added to that.

```
{{ block.innhold
| retconSrcset(
	[{ width: 400 },{ width : 800 },{ width : 1024 }],
	'img','100vw',true, {format: 'webp'}
) | retconRenameAttr('img', {
	srcset: 'data-srcset',
	sizes: 'data-sizes'
}) | retconAttr('img', {
	class: 'lazyload'
}) }}
```
Any settings added returns the same error, and the setup has worked until the last release.

Retcon 2.4.3
Craft 3.7.51
Imager-x 3.6.2
php 8.0.8

**Comment by mmikkel** [comment]
Nevermind, that code should've been more defensive :) 

Just released [Retcon v. 2.5.0](https://github.com/mmikkel/Retcon-Craft/releases/tag/2.5.0), which should resolve the problem.
