### ISSUE TITLE
retconChange fails with empty p tags

### ISSUE THREAD

**Issue by dillonbailey** [mmikkel/Retcon-Craft#49]
The workaround was to add a replace filter to strip the tags, but assuming not everyone will find this ideal:

`{{ block.heading | replace('/<[^\\/>][^>]*><\\/[^>]+>/', '') | retconChange('p', 'h2') }}`

Before implementing the workaround, the following error would be produced:
<img width="1665" alt="Screenshot 2023-02-17 at 1 04 09 pm" src="https://user-images.githubusercontent.com/1067872/219530936-a0217cec-5311-402d-bce2-11b6254c3c2d.png">

Based on the redactor field containing the following values in twig (without any filters):
```
<p dir="ltr"></p>
<p>An interesting heading</p>
<p></p>                
```

<img width="950" alt="Screenshot 2023-02-17 at 1 07 04 pm" src="https://user-images.githubusercontent.com/1067872/219531204-a5817b93-3c3f-489c-8663-8121adf4a27d.png">

**Comment by mmikkel** [comment]
Thanks for reporting that! Just published [Retcon v. 2.6.1](https://github.com/mmikkel/Retcon-Craft/releases/tag/2.6.1) with a fix.

**Comment by dillonbailey** [comment]
Amazing! Thanks @mmikkel
