### ISSUE TITLE
Retcon attr on a p element removes inline element children (anchor links).

### ISSUE THREAD

**Issue by turnstylerj** [mmikkel/Retcon-Craft#59]
When using Retcon attr on a paragraph element coming from the CMS as such:

```html
<p>This is a paragraph <a href="#">with a link</a>.</p>
```

```twig
{{ field|retcon([
	['attr', 'p', { class: 'test' } ],
]) }}
```

The resulting HTML output strips the inline link element, resulting in:

```html
<p class="test">This is a paragraph with a link.</p>
```

Am I just using Retcon incorrectly? Feels like I'm missing something looking through the documentation.

**Comment by mmikkel** [comment]
I'm not able to reproduce this. What kind of field is `field`? Which Retcon and Craft CMS versions are you running?

**Comment by turnstylerj** [comment]
Gah, sorry. Got this narrowed down and it wasn't actually a Retcon issue. Appreciate you testing!

**Comment by mmikkel** [comment]
Glad you got it sorted out, and thanks for the follow-up @turnstylerj!
