### ISSUE TITLE
Errors on image transforms

### ISSUE THREAD

**Issue by mmikkel** [mmikkel/Retcon-Craft#66]
Hi, we have a project with [_Imager_](https://plugins.craftcms.com/imager) and _Retcon_ plugins. We recently upgraded the _Retcon_ plugin to the version `2.7.0` and found that it's giving errors on image transforms:

<img width="950" alt="Screenshot 2023-10-27 at 5 03 05 PM" src="https://github.com/mmikkel/Retcon-Craft/assets/30666052/9189fae0-10e8-4b5a-8baa-0d7dace2da94">

### Additional info

- Craft version: 3.9.5
- Retcon plugin version: 2.7.0
- Imager plugin version: 2.4.0

_Originally posted by @anita-chouhan in https://github.com/mmikkel/Retcon-Craft/issues/38#issuecomment-1784765817_

**Comment by mmikkel** [comment]
Hi @anita-chouhan,

Thanks for reporting.

This looks like a compatibility issue with Imager, as the `safeFileFormats` was only added in Imager X (the successor to Imager, which is discontinued). I'll get that fixed as soon as I have the time – in the interim you might consider to

* Migrate to Imager X (https://plugins.craftcms.com/imager-x?craft3)
* Downgrade Retcon to version 2.6.1

Also: It's not going to fix this specific issue, If you choose to not downgrade Retcon, I highly recommend upgrading it to the latest release (2.7.4). There were a few regression errors introduced in 2.7.0 that have been fixed in subsequent releases.

**Comment by anita-chouhan** [comment]
Thank you for the suggestions. Upgrading to version `2.7.4` worked.

**Comment by mmikkel** [comment]
Hi @anita-chouhan, thanks for the follow-up. To be clear, are you saying that upgrading to Retcon 2.7.4 fixed the "Getting unknown property" exception you were getting before? Are you still running Imager 2.x?

**Comment by anita-chouhan** [comment]
Hello @mmikkel, sorry for the delayed response. We are still running _Imager_ 2.4.0 and  _Retcon_ 2.7.4, and it's working fine.

**Comment by mmikkel** [comment]
I was able to reproduce the issue using Craft 3.9.5 and Imager 2.4.0, and a fix has been implemented for the next Retcon release.

**Comment by mmikkel** [comment]
[Retcon v. 2.7.5](https://github.com/mmikkel/Retcon-Craft/releases/tag/2.7.5) is out now with that fix.
