### ISSUE TITLE
Craft 5 Beta Support

### ISSUE THREAD

**Issue by kylecotter** [mmikkel/Retcon-Craft#67]
Hi!

Possible to bump the composer require of Craft to include the 5 beta?

I sideloaded the plugin and nothing seems to have broken in Craft 5, so hopefully that's all that's needed to get this supported for Craft 5.

Thanks!

**Comment by mmikkel** [comment]
Just tagged Retcon v. 3.0.0-beta.1 with Craft 5 compatibility. A stable version will be tagged after Craft 5.0 GA is made available.

**Comment by kylecotter** [comment]
Great, thanks a bunch!
