### ISSUE TITLE
`:empty` selector in Retcon removes <br> elements incorrectly**

### ISSUE THREAD

**Issue by romainpoirier** [mmikkel/Retcon-Craft#70]
**Description:**

I'm using Retcon to modify my content, specifically to remove unnecessary tags. However, it seems that the CSS `:empty` selector is also targeting self-closing `<br>` elements when it shouldn't:

```twig
{{ entry.text | striptags('<br>') | retcon([
    ['remove', ':empty']
]) | typogrify }}
```

In this case, the `<br>` elements are being removed along with genuinely empty elements, which is unexpected behavior. 

Is this a bug? If not, how can I remove truly empty elements (e.g., `<p></p>`) while keeping `<br>` elements intact?

**Versions used:**
- `"craftcms/cms": "5.4.3"`
- `"mmikkel/retcon": "3.2.0"`

Thank you!

**Comment by mmikkel** [comment]
Retcon uses Symfony's [CssSelector component](https://symfony.com/doc/current/components/css_selector.html) under the hood, and I'm not sure if that supports the `:empty` selector (guessing not, though).

There's a dedicated [`retconRemoveEmpty`](https://github.com/mmikkel/Retcon-Craft/wiki/removeEmpty) filter for removing empty nodes, though. The default behavior for that is to retain any `<br>` tags; you might want to try that and see if it works better for your use case:

```twig
{{ entry.text | striptags('<br>') | retcon([
    ['removeEmpty']
]) | typogrify }}
```

**Comment by mmikkel** [comment]
That's interesting; I was not aware of that behaviour. It seems specific to CK Editor output, as I'm not able to reproduce it with Redactor, or with raw HTML (i.e. something like `'<p> </p>'|retconRemoveEmpty`.

I'll investigate; in the meantime if you need a quick fix you could do 

```twig
{{ entry.text | retconRemoveEmpty | replace('<p>&nbsp;</p>', '') | raw }}
```

**Comment by mmikkel** [comment]
@romainpoirier Retcon v. [2.8.2](https://github.com/mmikkel/Retcon-Craft/releases/tag/2.8.2) and [3.2.1](https://github.com/mmikkel/Retcon-Craft/releases/tag/3.2.1) is out with a fix for this now.
