### ISSUE TITLE
Composer conflicts with symfony/css-selector

### ISSUE THREAD

**Issue by monachilada** [mmikkel/Retcon-Craft#8]
There appears to be a conflict in installing the plugin via the command line. From what I can tell, one or other packages is using a newer version of the `symfony/css-selector` package, but as your package defines a specific version of 3.3.6 it throws some sort of conflict.

My guess would be that your composer file could require a `^3.3.6` or `~3.3.6` or something like that and it might solve the issue? I'm not a composer expert so I'm sorry if I'm missing something.

The feedback I'm getting when running `composer require mmikkel/retcon` is as follows:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/css-selector (locked at v3.4.21) -> satisfiable by symfony/css-selector[v3.4.21].
    - mmikkel/retcon 2.0.0 requires symfony/css-selector 3.3.6 -> satisfiable by symfony/css-selector[v3.3.6].
    - mmikkel/retcon 2.0.1 requires symfony/css-selector 3.3.6 -> satisfiable by symfony/css-selector[v3.3.6].
    - mmikkel/retcon 2.0.10 requires symfony/css-selector 3.3.6 -> satisfiable by symfony/css-selector[v3.3.6].
    - mmikkel/retcon 2.0.11 requires symfony/css-selector 3.3.6 -> satisfiable by symfony/css-selector[v3.3.6].
    - mmikkel/retcon 2.0.12 requires symfony/css-selector 3.3.6 -> satisfiable by symfony/css-selector[v3.3.6].
    - mmikkel/retcon 2.0.2 requires symfony/css-selector 3.3.6 -> satisfiable by symfony/css-selector[v3.3.6].
    - mmikkel/retcon 2.0.3 requires symfony/css-selector 3.3.6 -> satisfiable by symfony/css-selector[v3.3.6].
    - mmikkel/retcon 2.0.4 requires symfony/css-selector 3.3.6 -> satisfiable by symfony/css-selector[v3.3.6].
    - mmikkel/retcon 2.0.5 requires symfony/css-selector 3.3.6 -> satisfiable by symfony/css-selector[v3.3.6].
    - mmikkel/retcon 2.0.6 requires symfony/css-selector 3.3.6 -> satisfiable by symfony/css-selector[v3.3.6].
    - mmikkel/retcon 2.0.7 requires symfony/css-selector 3.3.6 -> satisfiable by symfony/css-selector[v3.3.6].
    - mmikkel/retcon 2.0.8 requires symfony/css-selector 3.3.6 -> satisfiable by symfony/css-selector[v3.3.6].
    - mmikkel/retcon 2.0.9 requires symfony/css-selector 3.3.6 -> satisfiable by symfony/css-selector[v3.3.6].
    - Conclusion: don't install symfony/css-selector v3.3.6
    - Installation request for mmikkel/retcon ^2.0 -> satisfiable by mmikkel/retcon[2.0.0, 2.0.1, 2.0.10, 2.0.11, 2.0.12, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9].
```

**Comment by mmikkel** [comment]
Hey @monachilada – thanks for contributing.

The reason why Retcon requires that specific version of `symfony/css-selector` is that later versions requires PHP 7.1. [Craft's starter Composer project](https://github.com/craftcms/craft) has a `platform` declaration of `"php": "7.0"` in its `composer.json` file, meaning that any projects bootstrapped using that starter project wouldn't be able to install Retcon without changing their `platform` declaration... since a lot of people are using the starter project, I opted for hard coding a dependency for the last version of CssSelector that required PHP 7.0.

That said, this isn't optimal. I'm also not a Composer expert, so there might be a way around this (maybe it's possible to require 3.3.6 for PHP 7.0 and a newer version for everything else? I'll look into it ASAP :)

**Comment by monachilada** [comment]
Ah, that makes sense. I was able to workaround it by also specifically requiring `3.3.6` in my own composer file, but time will tell if that has any unintended consequences for other packages requiring a later version. For now it's working fine for my use case. Thanks for the feedback.

**Comment by mmikkel** [comment]
Related: https://github.com/verbb/feed-me/issues/440#issuecomment-455729490

**Comment by nateiler** [comment]
Looking at the `composer.json` file.  I would expect to see semantic support of the symfony packages.  

```
"symfony/dom-crawler": "^3.3.6",
"symfony/css-selector": "^3.3.6"
```

You shouldn't see any breaking changes in any of the 3.x packages, but you would get any buy, security and performance improvements from releases > 3.3.6.

**Comment by mmikkel** [comment]
I've changed the Symfony package version constraints to use caret version range in [Retcon 2.2.1](https://github.com/mmikkel/Retcon-Craft/releases/tag/2.2.1) – hopefully this solves the issue.

**Comment by sweetroll** [comment]
Hi @mmikkel, now that the starter project uses Craft 3.6 which has its platform set to 7.2.5, would you be open to bumping the css-selector dependency to the latest (5.*)?

**Comment by mmikkel** [comment]
@sweetroll Sure, that's a good idea – look for a new release soonish, assuming there aren't any big breaking changes between CssSelector 3 and 5 😬

**Comment by sweetroll** [comment]
@mmikkel great! thanks for all your work.
